### ISSUE TITLE
Can we find trend also?

### ISSUE THREAD

**Issue by santoshanand** [ArtReeX/currency-pattern-detector#1]
For example current trend is Up trend or Down trend

**Comment by ArtReeX** [comment]
You can count the number of bull and bear trends in the answer and conclude that there will be more.

**Comment by santoshanand** [comment]
Would you please attache some screenshot for these patterns. I think individual method should also export for example bulishEngulfing(dataArray), bearishEngulfing(dataArray)

**Comment by ArtReeX** [comment]
Yes, you can check for individual patterns. [Example](https://github.com/ArtReeX/currency-pattern-detector/blob/master/source/spec/patterns/bullish/HaramiCrossSpec.ts)
